In [24]:
import numpy as np
a1 = np.array([2,1,3,4])
a2 = np.array([[2,1,4],[2,1,4],[2,1,4]])
a3 = np.array([[[2,1,4],[2,1,4],[2,1,4]],[[2,1,4],[2,1,4],[2,1,4]],[[2,1,4],[2,1,4],[2,1,4]]])

a4 = np.arange(10,50)
a5 = np.arange(10)
a6 = np.arange(.5,5,.25) #.25 distance

a7 = np.linspace(3,8,9) # split into 9 steps

ao1 = np.ones((2,2)) # fill marix with one

e1 = np.eye(4)

print(a4)
print(e1)
print(ao1)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1. 1.]
 [1. 1.]]
