In [38]:
import numpy as np
a1 = np.array([2,1,3,4])
a2 = np.array([[2,1,4],[2,5,4],[2,6,3]])
a3 = np.array([[[2,1,4],[2,1,4],[2,1,4]],[[2,1,4],[2,1,4],[2,1,4]],[[2,1,4],[2,1,4],[2,1,4]]])

a4 = np.arange(10,50)
a5 = np.arange(10)
a6 = np.arange(.5,5,.25) #.25 distance

a7 = np.linspace(3,8,9) # split into 9 steps

ao1 = np.ones((2,2)) # fill marix with one

e1 = np.eye(4)

print(a4)
print(e1)
print(ao1)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1. 1.]
 [1. 1.]]


In [28]:
ran1 = np.random.random((4,4)) #random matrix
print(ran1)

[[0.37596933 0.45815138 0.00979055 0.43140421]
 [0.19499476 0.90361759 0.64020696 0.57162793]
 [0.97213654 0.99782761 0.48901686 0.74391676]
 [0.3154247  0.35504838 0.91166385 0.50825225]]


In [29]:
print(ran1.ndim) #print matrix dimension

2


In [30]:
print(ran1.shape)

(4, 4)


In [31]:
print(ran1.size)

16


In [32]:
print(ran1.dtype)

float64


In [37]:
print(a1.reshape(2,2)) #make smaller matrix into new dimension

[[2 1]
 [3 4]]


In [51]:
print(a2)
print('------------')
print(a2[2:3])


[[2 1 4]
 [2 5 4]
 [2 6 3]]
------------
[[2 6 3]]


In [54]:
s1 = np.arange(5,15)
print(s1)
print(s1.max())
print(s1.min())
print(s1.cumsum())

[ 5  6  7  8  9 10 11 12 13 14]
14
5
[ 5 11 18 26 35 45 56 68 81 95]


In [55]:
x1 = np.linspace(0,180,10)
print(np.sin(x1))

[ 0.          0.91294525  0.74511316 -0.30481062 -0.99388865 -0.50636564
  0.58061118  0.98023966  0.21942526 -0.80115264]


In [58]:
x2 = np.arange(9).reshape(3,3)
print(x2)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [63]:
#multiplication of matrix

x3 = np.arange(6).reshape(3,2)
x4 = np.arange(10,16).reshape(2,3)
print(x3.dot(x4))

[[ 13  14  15]
 [ 59  64  69]
 [105 114 123]]
